function setdefaults()
%===============================================================================
% SETDEFAULTS
% Sets default figure property values for the root(0) object.
%
% MJRusso 10/2014
%===============================================================================

set(0, ...
'DefaultFigureColor', 'w',...
'DefaultAxesColor', 'w',...
'DefaultAxesFontName', 'Helvetica',...
'DefaultAxesFontSize',  18,...
'DefaultTextFontSize',  16,...
'DefaultTextFontName', 'Helvetica',...
'DefaultLineLineStyle', '-',...
'DefaultLineLineWidth', 1.5,...
'DefaultAxesUnits', 'normalized',...
'DefaultAxesLayer', 'Bottom');

end